### PR TITLE
Remove dependency on simplecov

### PR DESCRIPTION
**Pull request by vtnate**
Addresses #20 
We don't need this at all. Make it go away.

### CODE REVIEW

**Comment by nllong** [comment]
Yep, this can be removed. We can also remove the NREL fork from all the other repos now that they released an update that doesn’t require the native JSON gem

**Comment by vtnate** [comment]
🙌

**Comment by vtnate** [comment]
Hmmmm, regular simplecov 0.18 does indeed remove the dependency on json, but it is also dependent on Ruby >= 2.4. https://rubygems.org/gems/simplecov/versions/0.18.0

**Comment by nllong** [comment]
You are correct @vtnate. We can't remove simplecov until we move to OpenStudio 3.x. Do we need to revert this?

**Comment by vtnate** [comment]
I have put the NREL fork of simplecov back into example_files/Gemfile through other commits. I think I'd rather make a new PR that puts it back into the CLI Gemfile than revert this PR. I'll have that PR ready in a few minutes.

**Pull request merged**
