### PR TITLE
updated example_files/example_project.json  to include the electric d…

### PR DESCRIPTION
**Pull request by rawadelkontar**
…istribution network

### Pull Request Description

[description here]

### Checklist (Delete lines that don't apply)

- [ ] Unit tests have been added or updated
- [ ] All ci tests pass (green)
- [ ] An [issue](https://github.com/urbanopt/urbanopt-cli/issues) has been created (which will be used for the changelog)
- [ ] This branch is up-to-date with develop

### CODE REVIEW

**Review by vtnate — CHANGES_REQUESTED** [review]
@rawadelkontar Several of the existing buildings have specific details that you deleted with this change. Can you restore the EV charging and system_type fields for those buildings? They're visible in the changes here on github.

**Comment by kflemin** [comment]
@vtnate @rawadelkontar also I always pull from example project to update the cli example files so make sure they are correct/complete there as well. thanks!

**Review by vtnate — APPROVED** [review]
I like having a separate feature-file for the electrical stuff, just because it makes testing easier for us devs to use the original and only a few buildings. LGTM
:shipit:

**Comment by rawadelkontar** [comment]
@kflemin do you mean the geojson files in urbanopt-example-geojson-project repo? 
I added these as well there https://github.com/urbanopt/urbanopt-example-geojson-project/pull/92

**Pull request merged**
